BS-22 delete user
Maja9/blogService pull request #3
Opened 2021-11-02 14:31 UTC by Maja9

2021-11-02 14:50 UTC, marzgra requested changes
całkiem fajnie, popraw proszę komentarze :)

2021-11-02 14:50 UTC, marzgra commented on blogService/src/main/java/blogService/controler/UserController.java
> +        userService.deleteUser(userDto.getId(),userDto.getPassword());
pamiętaj o formatowaniu przed commitem (spacje między argumentami)

2021-11-02 14:50 UTC, marzgra commented on blogService/src/main/java/blogService/service/UserService.java
>          userToSave.setPassHash(userDto.getPassword().hashCode());
pamiętajo wcięciach w blokach

2021-11-02 14:50 UTC, marzgra commented on blogService/src/main/java/blogService/service/UserService.java
> +        if (password.hashCode() == userRepository.findById(userId).get().getPassHash()){
było by fajnie gdybyś najpierw upewniła się że user o podanym id istnieje, czyli:
1. pobierz usera o danym id (optional)
2. jdodaj warunek na początku IF że użytkownik jest obecny w bazie

2021-11-02 20:47 UTC, Maja9 commented
Zrobiłam poprawki, czy mogę mergować?

2021-11-02 21:29 UTC, marzgra approved these changes
możesz mergować, ale rozważ moje komentarze w następnym PR :)

2021-11-02 21:29 UTC, marzgra commented on blogService/src/main/java/blogService/controler/UserController.java
> +import javax.persistence.Column;
czy te importy są tu potrzebne?

2021-11-02 21:29 UTC, marzgra commented on blogService/src/main/java/blogService/service/UserService.java
> +            if (password.hashCode() == userRepository.findById(userId).get().getPassHash()) {
te warunki możesz połączyć w ramach jednego bloku IF za pomocą && (pamietaj aby sprawdzenie isPresent wystąpiło jako pierwsze)

2021-11-03 04:52 UTC, merged

2021-11-03 04:56 UTC, Maja9 commented on blogService/src/main/java/blogService/controler/UserController.java
> +import javax.persistence.Column;
Nie są używane, usunęłam również inne nieużywane w tej klasie importy

2021-11-03 04:58 UTC, Maja9 commented on blogService/src/main/java/blogService/service/UserService.java
> +            if (password.hashCode() == userRepository.findById(userId).get().getPassHash()) {
od razu lepsza czytelność, dzięki!