Newbranch
Maja9/blogService pull request #8
Opened 2021-11-17 14:00 UTC by Maja9

2021-11-17 22:47 UTC, marzgra requested changes

2021-11-17 22:47 UTC, marzgra commented on blogService/src/test/java/com/blog/blogService/mapper/UserMapperTest.java
> +        Assert.assertEquals(userDto.getUserName(), user.getName());
Pomyłeczka - powinno być user.getUserName() zamiast user.getName()
Czy w obecnej postaci test przeszedł pomyślnie?

2021-11-18 06:12 UTC, Maja9 commented on blogService/src/test/java/com/blog/blogService/mapper/UserMapperTest.java
> +        Assert.assertEquals(userDto.getUserName(), user.getName());
Poprawione (test byl na pomaranczowo, przyznaje ze zle sprawdzilam)

2021-11-18 08:03 UTC, marzgra approved these changes

2021-11-18 08:55 UTC, merged